replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  password: MYPASSWORD

resources: {}

# ConfigMap configuration for metrics.py
configMap:
  enabled: true
  name: metrics-py
  fileContent: |
    import collector
    import random
    import time

    def trigger_background_collection():
        delay = random.randint(0, 0)
        time.sleep(delay)
        collector.launch_collector()

# Volume configuration for mounting metrics.py
volumes:
  - name: metrics-py-volume
    configMap:
      name: cloudraft-metrics-py  # Avoid Helm templating in values.yaml

# Volume mount configuration for the main container
volumeMounts:
  - name: metrics-py-volume
    mountPath: /app/metrics.py
    subPath: metrics.py
