replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  pullPolicy: IfNotPresent
  tag: "1.0"

service:
  type: ClusterIP
  port: 8080

secrets:
  password: MYPASSWORD

command:
  - sh
  - -c
  - |
    sed -i 's/random.randint(180, 30)/random.randint(30, 180)/' /app/metrics.py && exec python /app/metrics.py
