replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  password: MYPASSWORD

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000  # Ensure this user exists in your container image
  runAsGroup: 3000  # Ensure this group exists in your container image

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3


volumes:
  - name: metrics-py-volume
    configMap:
      name: cloudraft-metrics-py
  - name: temp-volume
    emptyDir: {}

volumeMounts:
  - name: metrics-py-volume
    mountPath: /app/metrics.py
    subPath: metrics.py
  - name: temp-volume
    mountPath: /tmp
