replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  password: MYPASSWORD

resources: {}