apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  metrics.py: {{ .Values.configMap.fileContent | toYaml | nindent 4 }}
