apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metrics-app
  labels:
    app: {{ .Release.Name }}-metrics-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-metrics-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-metrics-app
    spec:
      containers:
        - name: metrics-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-metrics-secret
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}